[toolchain]
anchor_version = "1.0.2"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mock_swap = "DwA1q1BU2Mf4B9GQ7PWcQ1TiPHA5rhkR2et1Xr8CRzww"
pvp_trade = "2oQvjoTFEP8pyxhNgtSH7aCpoVfQK7wcWoQSLcQqE3wF"

[provider]
cluster = "Localnet"
wallet = ".anchor/local-wallet.json"
